version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    container_name: app
    depends_on:
      - db
    networks:
      - cosc304_network
  db:
    platform: linux/x86_64
    image: mysql:8.0.29
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cosc304
      MYSQL_DATABASE: cosc304
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - cosc304-db:/var/lib/mysql
    networks:
      - cosc304_network
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  cosc304-db:
networks:
  cosc304_network:
